name: "Security Scan"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Run Gosec Security Scanner                           // HL
        uses: securego/gosec@master                                // HL
        with:                                                      // HL
          args: '-fmt sarif -out results.sarif ./...'     // HL
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
